### ISSUE TITLE
We gotta migrate rigs data to be spec compliant

### ISSUE THREAD

**Issue by brunocalza** [tablelandnetwork/rigs#413] opened 2022-11-18 19:16 UTC
We dropped support for floating point numbers (see [Spec: we need to solve non-determinism for floating point columns](https://github.com/tablelandnetwork/docs/issues/27)). But the rigs data is using float point numbers for the `% Original` trait. 

Also, the `value` column of the `rig_attributes` table is of the type `ANY` and @asutula found the following behavior in the `ANY` column:

```
sqlite> create table foo (val any);
sqlite> insert into foo values (68.34);
sqlite> insert into foo values ('21.99');
sqlite> insert into foo values ('hi there');
sqlite> select typeof(val), val from foo;
real|68.34
real|21.99
text|hi there
```

A floating point number text is considered to have a `REAL` type inside an `ANY` column.

That means we would have to migrate the `rig_attributes` to another table that has a `TEXT` type for the value column and change the INSERT queries tuples from `(2804, 'number', '% Original', 63.33)` to `(2804, 'number', '% Original', '63.33')`.

Steps
- [ ] Check if marketplaces don't break with the type change
- [ ] Redeploy rigs data to use the text instead of float. That means a TEXT type column for type and value wrapped inside single quotes in tuples
- [ ] Update contract to point to new tables
- [ ] Drop support for `ANY` type (this would be in the parser)

See [discord conversation](https://discord.com/channels/592843512312102924/928435938361749536/1043212866511183942) and [the query where the problem was spotted](https://github.com/tablelandnetwork/rigs/files/10044303/insert.txt)

cc @sanderpick @jsign @asutula @carsonfarmer

**Comment by jsign** [comment] 2022-11-18 19:38
:heavy_plus_sign:

**Comment by sanderpick** [comment] 2022-11-18 20:38
@asutula I think `INT` is better suited for % Original. If we use `TEXT`, then it will no longer be a "stats" type trait, ie, a trait that can have a lower and upper filter range. We could simply round the values to `INT`, eg, 63.33 -> 63.

If that feels real messy... we could always do a test run to see if a string in a number trait work, but my guess it that it doesn't.

**Comment by asutula** [comment] 2022-11-18 21:48
Hey @sanderpick, the problem is that all attribute values are stored in our very simple, but very flexible table, `row_attributes`:
```
(
  rig_id integer not null,
  display_type text,
  trait_type text not null,
  value any not null,
  unique(rig_id, trait_type)
)
```
This provides flexibility because we can add additional attributes without changing the schema, but relies on `value` being of `any` type, or choosing a type that all attributes must conform to, like `text`. 

The reason I suggested that maybe `text` could work, even for text that is a floating point value, is because the table and queried metadata also specify the desired `display_type`, which in the case of `% Original` would still be `number`. I was hoping that the marketplaces would parse the value as a number and display it correctly. I think you are saying the same thing above. We'd need to test it, and yes, it feels messy.

So the other option is to sacrifice the flexibility of the current schema and make a "wide" attributes table with a column for each attribute, `% Original` would be INT, and those attributes would be fixed forever (we could always create a new attributes table with additional columns if needed, migrate the data, etc.).

Tough call.

**Comment by sanderpick** [comment] 2022-11-18 22:10
I see. I couldn't remember the use case for `ANY` in the tables. Makes sense.

Okay, I think we should use `display_type` of `string` and take the string value of the float and call it a day. This will change the trait layout, but feels like a less bad option than re-doing the table schema. 

At the same time, if you want to create a set of tables on mumbai that uses `display_type` of `number` and string values for the floats, i can deploy a contract and we can see what happens.

**Comment by asutula** [comment] 2022-11-18 22:28
Cool, might as well test it on mumbai and see. Will let you know once i push some data.

**Comment by asutula** [comment] 2022-11-19 00:25
For testing with the contract and Opensea, find the rigs data on mumbai with the attribute value column type as text (display_type is still number for % Original):
```
parts_80001_4038
layers_80001_4039
rig_attributes_80001_4040
lookups_80001_4041
```

**Comment by sanderpick** [comment] 2022-11-19 00:41
well, looks like that works fine! opensea is rounding the float to an int, so it must be treating it like a number.

from a freshly minted rig:

metadata query [here](https://testnet.tableland.network/query?extract=true&unwrap=true&s=select%20json_object(%27name%27%2C%27Rig%20%23%27%7C%7Crig_id%2C%27external_url%27%2C%27https%3A%2F%2Fgarage.tableland.xyz%2Frigs%2F%27%7C%7Crig_id%2C%27image%27%2C%27ipfs%3A%2F%2F%27%7C%7Crenders_cid%7C%7C%27%2F%27%7C%7Crig_id%7C%7C%27%2F%27%7C%7Cimage_full_name%2C%27image_alpha%27%2C%27ipfs%3A%2F%2F%27%7C%7Crenders_cid%7C%7C%27%2F%27%7C%7Crig_id%7C%7C%27%2F%27%7C%7Cimage_full_alpha_name%2C%27image_medium%27%2C%27ipfs%3A%2F%2F%27%7C%7Crenders_cid%7C%7C%27%2F%27%7C%7Crig_id%7C%7C%27%2F%27%7C%7Cimage_medium_name%2C%27image_medium_alpha%27%2C%27ipfs%3A%2F%2F%27%7C%7Crenders_cid%7C%7C%27%2F%27%7C%7Crig_id%7C%7C%27%2F%27%7C%7Cimage_medium_alpha_name%2C%27thumb%27%2C%27ipfs%3A%2F%2F%27%7C%7Crenders_cid%7C%7C%27%2F%27%7C%7Crig_id%7C%7C%27%2F%27%7C%7Cimage_thumb_name%2C%27thumb_alpha%27%2C%27ipfs%3A%2F%2F%27%7C%7Crenders_cid%7C%7C%27%2F%27%7C%7Crig_id%7C%7C%27%2F%27%7C%7Cimage_thumb_alpha_name%2C%27animation_url%27%2Canimation_base_url%7C%7Crig_id%7C%7C%27.html%27%2C%27attributes%27%2Cjson_insert((select%20json_group_array(json_object(%27display_type%27%2Cdisplay_type%2C%27trait_type%27%2Ctrait_type%2C%27value%27%2Cvalue))from%20rig_attributes_80001_4040%20where%20rig_id%3D10%20group%20by%20rig_id)%2C%27%24%5B%23%5D%27%2Cjson_object(%27display_type%27%2C%27string%27%2C%27trait_type%27%2C%27Garage%20Status%27%2C%27value%27%2Ccoalesce((select%20coalesce(end_time%2C%20%27in-flight%27)%20from%20pilot_sessions_80001_3821%20where%20rig_id%3D10%20and%20end_time%20is%20null)%2C%27parked%27))))%20from%20rig_attributes_80001_4040%20join%20lookups_80001_4041%20where%20rig_id%3D10%20group%20by%20rig_id%3B)

opensea link: https://testnets.opensea.io/assets/mumbai/0xa04ac9ca2fe3db8f372b1364cdad6fc58453fde8/10

**Comment by asutula** [comment] 2022-11-19 18:24
Cool! Looks like there is some weird thing happening where `0.58` is ending up as `57.99999999999999%` when written to Tableland. I'll get that precision issue sorted out. Glad this will work.

**Comment by asutula** [comment] 2022-11-21 23:24
Ok here's a PR that implements the fix https://github.com/tablelandnetwork/rigs/pull/423.

Once that is merged, we'll need to create the new Rigs attributes table on Arbirum Goerli and write data to it. Tracking that in #420 and then update the Rigs contract to use that new table, tracking in #421.

**Comment by asutula** [comment] 2022-11-23 19:13
Ok, the Rigs data is now compliant. The new attributes table is `rig_attributes_42161_15`.

Closing this.

**Closed by asutula** 2022-11-23 19:13 UTC

**Comment by carsonfarmer** [comment] 2022-11-29 23:38
Hey gang, revisiting this issue. So it actually seems like, due to the quirks of SQLite discovered above, we can't really support the `ANY` type either... can we? Because this seems "bad":

> ```
> sqlite> create table foo (val any);
> sqlite> insert into foo values (68.34);
> sqlite> insert into foo values ('21.99');
> sqlite> insert into foo values ('hi there');
> sqlite> select typeof(val), val from foo;
> real|68.34
> real|21.99
> text|hi there
> ```
> A floating point number text is considered to have a REAL type inside an ANY column.
>

**Comment by asutula** [comment] 2022-11-29 23:47
Just for my own understanding... Where does the floating point math problem happen? Is it in the SQLite db layer or in the Golang parser/AST layer where parts of the query string are converted to Go `float64` values?

**Comment by brunocalza** [comment] 2022-11-30 00:40
> Hey gang, revisiting this issue. So it actually seems like, due to the quirks of SQLite discovered above, we can't really support the `ANY` type either... can we? Because this seems "bad":

Yeah. The `ANY` type seems unsafe to me. It opens a door for someone trying something that messes up with our database state. 

> Just for my own understanding... Where does the floating point precision problem happen?

When we first found a problem with FLOATs, it was at the CPU architecture layer. If I remember correctly, my M1 Mac was generating a different Tableland database state than Ignacio's Intel Ubuntu and Intel Mac for a specific query. Not sure if the problem can happen in the same CPU architecture. Although the floating point math has rounding errors, I guess that SQLite would execute deterministically in the same CPU architecture.

**Comment by brunocalza** [comment] 2022-11-30 00:47
Interesting comment about a floating point issue in Golang repo (not related to SQLite, but just to illustrate the problem from another angle): 
> We do not guarantee identical floating-point behavior across architectures, as the spec describes.
If you need that, you would need to add casts in the appropriate places.

https://github.com/golang/go/issues/44528#issuecomment-783979826
